// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiEiey_7Qd0aUN_86ndSuVRuB9Ut9No0M',
    appId: '1:646747861074:web:f0a01c13dff0c4d164ef8b',
    messagingSenderId: '646747861074',
    projectId: 'asthmatic-ci',
    authDomain: 'asthmatic-ci.firebaseapp.com',
    storageBucket: 'asthmatic-ci.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBLh0ROT4nF55i3uVV3nK6W3wCvVliis',
    appId: '1:646747861074:android:d2402eb18d47d47a64ef8b',
    messagingSenderId: '646747861074',
    projectId: 'asthmatic-ci',
    storageBucket: 'asthmatic-ci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYjvc2m-aBkoJxdgBVH3Kt9sB5PPfo_O0',
    appId: '1:646747861074:ios:c71d1a2702a160b464ef8b',
    messagingSenderId: '646747861074',
    projectId: 'asthmatic-ci',
    storageBucket: 'asthmatic-ci.firebasestorage.app',
    iosBundleId: 'com.example.recenteVersionAths',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYjvc2m-aBkoJxdgBVH3Kt9sB5PPfo_O0',
    appId: '1:646747861074:ios:c71d1a2702a160b464ef8b',
    messagingSenderId: '646747861074',
    projectId: 'asthmatic-ci',
    storageBucket: 'asthmatic-ci.firebasestorage.app',
    iosBundleId: 'com.example.recenteVersionAths',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiEiey_7Qd0aUN_86ndSuVRuB9Ut9No0M',
    appId: '1:646747861074:web:35a9de7d3788eed164ef8b',
    messagingSenderId: '646747861074',
    projectId: 'asthmatic-ci',
    authDomain: 'asthmatic-ci.firebaseapp.com',
    storageBucket: 'asthmatic-ci.firebasestorage.app',
  );

}